config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: 'registrations'}
  resources :posts, only: [:new, :create, :index, :destroy]
  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  validates :content, presence: true
  validates :member_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, only: [:new, :create]
  before_action :set_post, only: [:destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = current_member.posts.build
  end

  def create
    @post = current_member.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    # prevent deletion of another member's post unless logged in as that member
    # delete link is hidden in view. This prevents @post deletions using curl requests
    if correct_member
      @post.destroy
      flash[:success] = "Post deleted."
    end
    redirect_to root_path
  end

  private

    def post_params
      params.require(:post).permit(:content)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def correct_member
      current_member == @post.member
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

     def sign_up_params
       params.require(:member).permit(:name, :username, :email, :password, :password_confirmation)
     end

     def account_update_params
       params.require(:member).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <p class=<% message_type %> >
        <%= message %>
      </p>
    <% end %>
    <div class="links">
      <% if member_signed_in? %>
        <div class="current-member-username">
          Logged in as <%= link_to "#{current_member.username}", edit_member_registration_path(current_member) %>
        </div>
        <%= link_to "New Post", new_post_path %>
        <%= link_to "Logout", destroy_member_session_path, method: :delete %>
      <% else %>
        <h1>Welcome to Members Only!</h1>
        <div class="login-signup">
        <% if current_page?(root_path) %>
          <p>You can
          <%= link_to "Login", new_member_session_path %>
          or
          <%= link_to "Sign Up", new_member_registration_path %>
        <% end %>
          </p>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2 class="header">Member Posts</h2>
<% @posts.each do |post| %>
  <ul>
    <li>
      <% if member_signed_in? %>
        <p>Post Author: <%= post.member.name %> | <span>Posted <%= time_ago_in_words(post.created_at) %> ago. </span></p>
      <% else %>
        <p><em>Author name visible to Members only.</em></p>
      <% end %>
      <p class="post-content">
        <%= post.content %>
        <div>
          <% if current_member == post.member %>
            <%= link_to "delete", post, method: :delete,
                                        data: {test_id: "#{current_member.name}-post", 
                                        confirm: "Are you sure you want to delete this post?" } %>
          <% end %>
        </div>
      </p>
    </li>
  </ul>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  
  <%= form.text_area :content, class: "text-box", placeholder: "Write a new post" %>
  <%= form.submit "Submit", id: "submit-button" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error-box">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>